{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "flink.fullname" . }}
  labels:
    app: {{ include "flink.labels.app" . }}
    chart: {{ include "flink.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "flink.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "flink.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
