{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "flink.fullname" . }}
  labels:
    app: {{ include "flink.labels.app" . }}
    chart: {{ include "flink.labels.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "delete", "update"]
{{- end }}
